"""drop recurring_orders table

Revision ID: 3c3667b83272
Revises: 6de1b88d1480
Create Date: 2026-07-14 13:34:51.458034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c3667b83272'
down_revision = '6de1b88d1480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recurring_orders_client_id', table_name='recurring_orders')
    op.drop_index('ix_recurring_orders_distributor_id', table_name='recurring_orders')
    op.drop_index('ix_recurring_orders_point_id', table_name='recurring_orders')
    op.drop_table('recurring_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_orders',
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('point_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('distributor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='recurring_orders_client_id_fkey'),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name='recurring_orders_distributor_id_fkey'),
    sa.ForeignKeyConstraint(['last_order_id'], ['orders.id'], name='recurring_orders_last_order_id_fkey'),
    sa.ForeignKeyConstraint(['point_id'], ['points_of_sale.id'], name='recurring_orders_point_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recurring_orders_pkey')
    )
    op.create_index('ix_recurring_orders_point_id', 'recurring_orders', ['point_id'], unique=False)
    op.create_index('ix_recurring_orders_distributor_id', 'recurring_orders', ['distributor_id'], unique=False)
    op.create_index('ix_recurring_orders_client_id', 'recurring_orders', ['client_id'], unique=False)
    # ### end Alembic commands ###
