"""add payment_url and recurring_orders

Revision ID: 6de1b88d1480
Revises: c9f20a54031f
Create Date: 2026-07-13 19:04:39.973639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de1b88d1480'
down_revision = 'c9f20a54031f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_orders',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_order_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['last_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points_of_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_orders_client_id'), 'recurring_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_recurring_orders_distributor_id'), 'recurring_orders', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_recurring_orders_point_id'), 'recurring_orders', ['point_id'], unique=False)
    op.add_column('orders', sa.Column('payment_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_url')
    op.drop_index(op.f('ix_recurring_orders_point_id'), table_name='recurring_orders')
    op.drop_index(op.f('ix_recurring_orders_distributor_id'), table_name='recurring_orders')
    op.drop_index(op.f('ix_recurring_orders_client_id'), table_name='recurring_orders')
    op.drop_table('recurring_orders')
    # ### end Alembic commands ###
