"""initial schema

Revision ID: c9f20a54031f
Revises: 
Create Date: 2026-07-13 12:19:46.306980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f20a54031f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('distributors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contacts', sa.String(length=500), nullable=True),
    sa.Column('onec_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributors_login_email'), 'distributors', ['login_email'], unique=True)
    op.create_table('clients',
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_distributor_id'), 'clients', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.create_table('products',
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('base_price_with_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_distributor_id'), 'products', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_products_external_code'), 'products', ['external_code'], unique=False)
    op.create_table('sync_logs',
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('catalog', 'payments', 'manual', name='sync_type'), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', name='sync_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_distributor_id'), 'sync_logs', ['distributor_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_thread_per_client')
    )
    op.create_index(op.f('ix_chat_threads_client_id'), 'chat_threads', ['client_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_distributor_id'), 'chat_threads', ['distributor_id'], unique=False)
    op.create_table('invitations',
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'used', 'expired', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by_client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['used_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_code'), 'invitations', ['code'], unique=True)
    op.create_index(op.f('ix_invitations_distributor_id'), 'invitations', ['distributor_id'], unique=False)
    op.create_table('points_of_sale',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deferment_until', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_of_sale_client_id'), 'points_of_sale', ['client_id'], unique=False)
    op.create_index(op.f('ix_points_of_sale_distributor_id'), 'points_of_sale', ['distributor_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('client', 'distributor', name='chat_sender'), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('orders',
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('distributor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending_1c', 'sent_to_1c', 'cancelled', name='order_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('none', 'unpaid', 'paid', name='payment_status'), nullable=False),
    sa.Column('payment_status_manual', sa.Boolean(), nullable=False),
    sa.Column('cancel_comment', sa.String(length=1000), nullable=True),
    sa.Column('onec_document_id', sa.String(length=128), nullable=True),
    sa.Column('send_attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points_of_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_distributor_id'), 'orders', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_orders_point_id'), 'orders', ['point_id'], unique=False)
    op.create_table('point_product_prices',
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('manual_price_with_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points_of_sale.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id', 'product_id', name='uq_point_product')
    )
    op.create_index(op.f('ix_point_product_prices_point_id'), 'point_product_prices', ['point_id'], unique=False)
    op.create_index(op.f('ix_point_product_prices_product_id'), 'point_product_prices', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price_with_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_point_product_prices_product_id'), table_name='point_product_prices')
    op.drop_index(op.f('ix_point_product_prices_point_id'), table_name='point_product_prices')
    op.drop_table('point_product_prices')
    op.drop_index(op.f('ix_orders_point_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_distributor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_points_of_sale_distributor_id'), table_name='points_of_sale')
    op.drop_index(op.f('ix_points_of_sale_client_id'), table_name='points_of_sale')
    op.drop_table('points_of_sale')
    op.drop_index(op.f('ix_invitations_distributor_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_chat_threads_distributor_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_client_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_sync_logs_distributor_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_products_external_code'), table_name='products')
    op.drop_index(op.f('ix_products_distributor_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_distributor_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_distributors_login_email'), table_name='distributors')
    op.drop_table('distributors')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
